#+TITLE: EmacsGME Readme

* EmacsGME - Emacs Games Master Emulator

EmacsGME v0.1

* Introduction

EmacsGME is a gamesmaster emulator in the style of MythicGME/CRGE/etc, produced in emacs-lisp for playing solo-roleplaying games entirely within text/org-mode documents.

As this is my first real use of emacs-lisp, a lot of it is just me trying out different things in a literate-programming style, with my exploratory document eventually due to tangle into an emacs-lisp file for easy addition into any emacs-setup.

* Installation

This will have to be manually added for the time being, as I want to flesh out more features before this is submitted to MELPA.
For now, the simplest way to add this to your install is to clone this repo, and place the following into you emacs config:-
#+BEGIN_SRC
(load-file "/path/to/egme.el")
#+END_SRC
Be sure to put in the correct path for where your copy of ~egme.el~ is saved.

* Usage

Usage should be easy to gleam by reading the ~egme.org~ - I hae tried to heavily document each function, not just in how it works but how I hope to extend in the future.

** Dice Roller

The first main feature is the dice roller, the function ~egme-roll-dice~. This can either be called with ~M-x egme-roll-dice~, or by the default keybind of ~C-c g r~.
After calling, the user is asked to input a dice roll into the mini-buffer. This is to be input as per any usual RPG dice roll, with a modifier, without spaces. Examples of valid choices are:-
- 1d20
- 2D6+3
- d666
- 3d10-5
This will accept any numbers for the dice type, and will roll dice with that range of numbers. This is only treated differently when using multiple-6 dice (D66,D666,D6666...) - in those cases, it will roll that many 6-sided dice and combine them for each digit of the result.
Hit return, and the results will be printed into the current buffer like these examples:-
#+BEGIN_QUOTE
~~|Games Master|~~~~~~~~~
Rolled:  2d12+8
Result:  20
~~~~~~~~~~~~~~~~~~~~~~~~~
#+END_QUOTE
#+BEGIN_QUOTE
~~|Games Master|~~~~~~~~~
Rolled:  1d666
Result:  646
~~~~~~~~~~~~~~~~~~~~~~~~~
#+END_QUOTE


* TO-DO List

The following items are currently on the todo list, but I am open to suggestions of how this can be further expanded.

- Handling a list of NPCs
- Handling a list of threads

  
* Licensing

This is licensed under the GPLv2, see included licence file for details.
